# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:13
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20170322_1141'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
